// Generates src/styles/tokens.css from src/styles/tokens.json (the design system's mirror).
// `pnpm tokens` writes it; `pnpm tokens --check` fails when the file is stale.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type Themed = { light: string; dark: string };
type ColorToken = { name: string; value: Themed | string };
type SimpleToken = { name: string; value: string };
type ThemedShadow = { name: string; value: Themed };
type TypeStyle = {
  name: string;
  fontSize: string;
  lineHeight: string;
  fontWeight: number;
};

export type Tokens = {
  color: { tokens: ColorToken[] };
  type: {
    families: { sans: string; mono: string };
    groups: { family: "sans" | "mono"; styles: TypeStyle[] }[];
  };
  spacing: { tokens: SimpleToken[] };
  radius: { tokens: SimpleToken[] };
  shadow: { tokens: ThemedShadow[] };
  size: { tokens: SimpleToken[] };
  breakpoint: { tokens: SimpleToken[] };
};

const here = dirname(fileURLToPath(import.meta.url));
const jsonPath = resolve(here, "../src/styles/tokens.json");
const cssPath = resolve(here, "../src/styles/tokens.css");

const isAlias = (v: string) => /^\{[a-z0-9-]+\}$/.test(v);
const aliasOf = (v: string) => `var(--${v.slice(1, -1)})`;

export function resolveColor(token: ColorToken, theme: "light" | "dark"): string {
  if (typeof token.value === "string") {
    if (!isAlias(token.value)) throw new Error(`${token.name}: not an alias or a themed value`);
    return aliasOf(token.value);
  }
  return token.value[theme];
}

function themeVars(t: Tokens, theme: "light" | "dark", indent: string): string[] {
  const lines = [`${indent}color-scheme: ${theme};`];
  for (const c of t.color.tokens) lines.push(`${indent}--${c.name}: ${resolveColor(c, theme)};`);
  for (const s of t.shadow.tokens) lines.push(`${indent}--${s.name}: ${s.value[theme]};`);
  return lines;
}

function typeClass(style: TypeStyle, family: "sans" | "mono"): string {
  const lines = [
    `  font-family: var(--font-${family});`,
    `  font-size: ${style.fontSize};`,
    `  line-height: ${style.lineHeight};`,
    `  font-weight: ${style.fontWeight};`,
  ];
  if (family === "mono") lines.push("  font-variant-numeric: tabular-nums;");
  return `.${style.name} {\n${lines.join("\n")}\n}`;
}

export function generate(t: Tokens): string {
  const fixed = (tokens: SimpleToken[]) =>
    tokens.map((x) => `  --${x.name}: ${x.value};`);
  const root = [
    "  --font-sans: " + t.type.families.sans + ";",
    "  --font-mono: " + t.type.families.mono + ";",
    ...fixed(t.spacing.tokens),
    ...fixed(t.radius.tokens),
    ...fixed(t.size.tokens),
    ...fixed(t.breakpoint.tokens),
    ...themeVars(t, "light", "  "),
  ];
  const dark = themeVars(t, "dark", "  ");
  const classes = t.type.groups.flatMap((g) => g.styles.map((s) => typeClass(s, g.family)));
  return [
    "/* Generated by web/scripts/tokens.ts from tokens.json. Do not edit by hand. */",
    `:root,\n[data-theme="light"] {\n${root.join("\n")}\n}`,
    `[data-theme="dark"] {\n${dark.join("\n")}\n}`,
    `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n${themeVars(t, "dark", "    ").join("\n")}\n  }\n}`,
    ...classes,
    "",
  ].join("\n\n").replace(/\n\n$/, "\n");
}

function main() {
  const tokens = JSON.parse(readFileSync(jsonPath, "utf8")) as Tokens;
  const css = generate(tokens);
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(cssPath, "utf8");
    } catch {
      /* missing counts as stale */
    }
    if (current !== css) {
      console.error("tokens.css is stale: run `pnpm tokens`");
      process.exit(1);
    }
    return;
  }
  writeFileSync(cssPath, css);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
