// The only door to Phosphor Regular: exactly the design system's allowlist (Icons asset group).
// Each icon has one meaning there. To add one, add it to the design system first, then here.
export {
  ArrowClockwise,
  ArrowSquareOut,
  CaretDown,
  CaretRight,
  Check,
  Circle,
  CircleHalf,
  Copy,
  CopySimple,
  Cpu,
  DotsSixVertical,
  GraphicsCard,
  Info,
  LockSimple,
  LockSimpleOpen,
  MagnifyingGlass,
  Minus,
  Moon,
  PencilSimple,
  Pause,
  Play,
  Plus,
  Prohibit,
  SealCheck,
  Stop,
  Sun,
  Trash,
  Warning,
  X,
} from "@phosphor-icons/react";
