# Generated by `python -m nanoscope.blocks.stubs`; do not edit by hand.
from typing import overload

import torch
import torch.nn as nn

from nanoscope.blocks.spec import BlockSpec
from nanoscope.blocks.attention import Attention as _Attention
from nanoscope.blocks.composite import Composite as Composite
from nanoscope.blocks.composite import Residual as _Residual
from nanoscope.blocks.embedding import LearnedPosition as _LearnedPosition
from nanoscope.blocks.embedding import TokenEmbedding as _TokenEmbedding
from nanoscope.blocks.head import Head as _Head
from nanoscope.blocks.mlp import GELUMLP as _GELUMLP
from nanoscope.blocks.mlp import SwiGLU as _SwiGLU
from nanoscope.blocks.moe import MoE as _MoE
from nanoscope.blocks.norm import LayerNorm as _LayerNorm
from nanoscope.blocks.norm import RMSNorm as _RMSNorm
from nanoscope.blocks.positional import ALiBi as _ALiBi
from nanoscope.blocks.positional import NoPE as _NoPE
from nanoscope.blocks.positional import RoPE as _RoPE
from nanoscope.blocks.primitives import Activation as _Activation
from nanoscope.blocks.primitives import CausalMask as _CausalMask
from nanoscope.blocks.primitives import Linear as _Linear
from nanoscope.blocks.primitives import MergeHeads as _MergeHeads
from nanoscope.blocks.primitives import ScaledDotScores as _ScaledDotScores
from nanoscope.blocks.primitives import Softmax as _Softmax
from nanoscope.blocks.primitives import SplitHeads as _SplitHeads
from nanoscope.blocks.primitives import WeightedSum as _WeightedSum
from nanoscope.blocks.registry import BlockInfo as BlockInfo
from nanoscope.blocks.registry import register_block as register_block
from nanoscope.blocks.spec import BlockModule as BlockModule
from nanoscope.blocks.spec import BlockSpec as BlockSpec
from nanoscope.blocks.structure import Block as _Block
from nanoscope.blocks.structure import Decoder as Decoder
from nanoscope.blocks.templates.attention import AttentionTemplate as _AttentionTemplate
from nanoscope.blocks.templates.block import BlockTemplate as _BlockTemplate

class ALiBi(_ALiBi):
    @overload
    def __new__(cls) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int) -> ALiBi: ...

class Activation(_Activation):
    @overload
    def __new__(cls, *, kind: str = ...) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int, kind: str = ...) -> Activation: ...

class Attention(_Attention):
    @overload
    def __new__(cls, *, n_heads: int, n_kv_heads: int | None = ..., pos: BlockSpec | nn.Module | None = ..., qk_norm: bool = ..., window: int | None = ..., bias: bool = ...) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int, n_heads: int, n_kv_heads: int | None = ..., pos: BlockSpec | nn.Module | None = ..., qk_norm: bool = ..., window: int | None = ..., bias: bool = ...) -> Attention: ...

class AttentionTemplate(_AttentionTemplate):
    @overload
    def __new__(cls, *, q: BlockSpec | nn.Module, k: BlockSpec | nn.Module, v: BlockSpec | nn.Module, scores: BlockSpec | nn.Module, mask: BlockSpec | nn.Module, normalize: BlockSpec | nn.Module, mix: BlockSpec | nn.Module, out: BlockSpec | nn.Module) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int, q: BlockSpec | nn.Module, k: BlockSpec | nn.Module, v: BlockSpec | nn.Module, scores: BlockSpec | nn.Module, mask: BlockSpec | nn.Module, normalize: BlockSpec | nn.Module, mix: BlockSpec | nn.Module, out: BlockSpec | nn.Module) -> AttentionTemplate: ...

class Block(_Block):
    @overload
    def __new__(cls, *, norm: BlockSpec, attn: BlockSpec, mlp: BlockSpec, order: str = ...) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int, norm: BlockSpec, attn: BlockSpec, mlp: BlockSpec, order: str = ...) -> Block: ...

class BlockTemplate(_BlockTemplate):
    @overload
    def __new__(cls, *, norm1: BlockSpec | nn.Module, attn: BlockSpec | nn.Module, norm2: BlockSpec | nn.Module, mlp: BlockSpec | nn.Module) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int, norm1: BlockSpec | nn.Module, attn: BlockSpec | nn.Module, norm2: BlockSpec | nn.Module, mlp: BlockSpec | nn.Module) -> BlockTemplate: ...

class CausalMask(_CausalMask):
    @overload
    def __new__(cls) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int) -> CausalMask: ...

class GELUMLP(_GELUMLP):
    @overload
    def __new__(cls, *, hidden: int | None = ..., bias: bool = ...) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int, hidden: int | None = ..., bias: bool = ...) -> GELUMLP: ...

class Head(_Head):
    @overload
    def __new__(cls, *, vocab_size: int) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int, vocab_size: int) -> Head: ...

class LayerNorm(_LayerNorm):
    @overload
    def __new__(cls, *, bias: bool = ..., eps: float = ...) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int, bias: bool = ..., eps: float = ...) -> LayerNorm: ...

class LearnedPosition(_LearnedPosition):
    @overload
    def __new__(cls) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int) -> LearnedPosition: ...

class Linear(_Linear):
    @overload
    def __new__(cls, *, in_features: int | None = ..., out_features: int | None = ..., bias: bool = ...) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int, in_features: int | None = ..., out_features: int | None = ..., bias: bool = ...) -> Linear: ...

class MergeHeads(_MergeHeads):
    @overload
    def __new__(cls) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int) -> MergeHeads: ...

class MoE(_MoE):
    @overload
    def __new__(cls, *, experts: int = ..., top_k: int = ..., hidden: int | None = ..., aux_loss: float = ...) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int, experts: int = ..., top_k: int = ..., hidden: int | None = ..., aux_loss: float = ...) -> MoE: ...

class NoPE(_NoPE):
    @overload
    def __new__(cls) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int) -> NoPE: ...

class RMSNorm(_RMSNorm):
    @overload
    def __new__(cls, *, eps: float = ...) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int, eps: float = ...) -> RMSNorm: ...

class Residual(_Residual):
    @overload
    def __new__(cls, *, inner: BlockSpec | nn.Module) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int, inner: BlockSpec | nn.Module) -> Residual: ...

class RoPE(_RoPE):
    @overload
    def __new__(cls, *, base: float = ...) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int, base: float = ...) -> RoPE: ...

class ScaledDotScores(_ScaledDotScores):
    @overload
    def __new__(cls) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int) -> ScaledDotScores: ...

class Softmax(_Softmax):
    @overload
    def __new__(cls) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int) -> Softmax: ...

class SplitHeads(_SplitHeads):
    @overload
    def __new__(cls, *, n_heads: int) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int, n_heads: int) -> SplitHeads: ...

class SwiGLU(_SwiGLU):
    @overload
    def __new__(cls, *, hidden: int | None = ...) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int, hidden: int | None = ...) -> SwiGLU: ...

class TokenEmbedding(_TokenEmbedding):
    @overload
    def __new__(cls, *, vocab_size: int) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int, vocab_size: int) -> TokenEmbedding: ...

class WeightedSum(_WeightedSum):
    @overload
    def __new__(cls) -> BlockSpec: ...
    @overload
    def __new__(cls, *, d_model: int, context_length: int) -> WeightedSum: ...
