"""Type stubs for `nanoscope.blocks`, generated from the blocks' own signatures.

The package exports its names lazily (`__getattr__`, so a block can be locked at import), which
leaves a type checker with `Any` for every block, and `BlockModule.__new__` returns `Any` so a
call with options only (`Attention(n_heads=4)`, a `BlockSpec`) is never checked. The generated
`nanoscope/blocks/__init__.pyi` names every export and gives each block two keyword-only
overloads: options only (a `BlockSpec`) and options with `d_model` and `context_length` (a
module). Nothing changes at run time; only type checkers (and the editor's language server) read
the stub.

    python -m nanoscope.blocks.stubs          write nanoscope/blocks/__init__.pyi
    python -m nanoscope.blocks.stubs --check  fail if the file is out of date
"""

from __future__ import annotations

import importlib
import inspect
import sys
from pathlib import Path

HEADER = '''\
# Generated by `python -m nanoscope.blocks.stubs`; do not edit by hand.
from typing import overload

import torch
import torch.nn as nn

from nanoscope.blocks.spec import BlockSpec
'''
SLOT_TYPE = "BlockSpec | nn.Module"


def _option(name: str, param: inspect.Parameter, slot: bool) -> str:
    annotation = SLOT_TYPE if slot or param.annotation is inspect.Parameter.empty \
        else str(param.annotation)
    if param.default is inspect.Parameter.empty:
        return f"{name}: {annotation}"
    return f"{name}: {annotation} = ..."


def render() -> str:
    from nanoscope.blocks.composite import Composite
    from nanoscope.blocks.spec import BlockModule, _options

    # not `from nanoscope.blocks import ...`: type checkers read this package through the stub
    exports: dict[str, str] = importlib.import_module("nanoscope.blocks")._EXPORTS
    imports: list[str] = []
    body: list[str] = []
    for name, module in sorted(exports.items()):
        cls = getattr(importlib.import_module(module), name)
        is_block = (isinstance(cls, type) and issubclass(cls, BlockModule)
                    and cls not in (BlockModule, Composite))
        if not is_block:
            imports.append(f"from {module} import {name} as {name}")
            continue
        imports.append(f"from {module} import {name} as _{name}")
        slots = getattr(cls, "SLOTS", None) is not None
        options = []
        for key, param in _options(cls).items():
            if slots:  # a template's slots are all required keyword arguments
                param = inspect.Parameter(key, inspect.Parameter.KEYWORD_ONLY)
            options.append(_option(key, param, slots))
        ordered = sorted(options, key=lambda o: "= ..." in o)  # required before defaulted
        spec_args = ", ".join(["cls", "*", *ordered] if ordered else ["cls"])
        module_args = ", ".join(["cls", "*", "d_model: int", "context_length: int", *ordered])
        body.append(
            f"class {name}(_{name}):\n"
            f"    @overload\n"
            f"    def __new__({spec_args}) -> BlockSpec: ...\n"
            f"    @overload\n"
            f"    def __new__({module_args}) -> {name}: ...\n")
    lines = [HEADER.rstrip("\n"), *sorted(imports, key=lambda i: i.split(" import ")[0]), "", *body]
    return "\n".join(lines).rstrip("\n") + "\n"


def stub_path() -> Path:
    return Path(__file__).with_name("__init__.pyi")


def main(argv: list[str]) -> int:
    text = render()
    path = stub_path()
    if "--check" in argv:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != text:
            print(f"{path} is out of date: run `python -m nanoscope.blocks.stubs`")
            return 1
        return 0
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
